### ISSUE TITLE
DocIssuance_IssueTicket not adding RF

### ISSUE THREAD

**Issue by fayax** [amabnl/amadeus-ws-client#14]
I get this with DocIssuance_IssueTicket. Received From not adding automatically?

Amadeus\Client\Result Object
(
    [status] => ERR
    [messages] => Array
        (
            [0] => Amadeus\Client\Result\NotOk Object
                (
                    [code] => 96
                    [text] => NEED RECEIVED FROM
                    [level] => 
                )

        )

**Comment by DerMika** [comment]
Hello, 

This sounds like a workflow issue. I am not aware that the message `DocIssuance_IssueTicket ` message can throw his error. In fact, you cannot provide an RF element in the DocIssuance_IssueTicket message.

Usually `NEED RECEIVED FROM` is an error originating from a `PNR_AddMultiElements`, or some kind of operation on a PNR in context - after which the PNR must be saved with an RF element to indicate which entity made the change. The error `NEED RECEIVED FROM` will then occur when you're trying to save the updated PNR *(if a RECEIVED FROM element was not provided)*. 

When you do a PNR_AddMultiElements operation with this library, it should automatically add an RF field if you didn't provide an explicit RF element in your operation. 

In order to diagnose your specific error, I would have to take a look at the operations you were doing on the PNR in question. 

In any case, I don't think the error message is related to the DocIssuance_IssueTicket message: this error is not listed in the Error Messages section of the documentation of DocIssuance_IssueTicket.

You'll need to investigate which PNR operations you are doing on the PNR you have in context. If - besides performing the ticket issue entries - you are doing other changes to the PNR, you'll have to manually add an RF field using a PNR_AddMultiElements message.

**Comment by fayax** [comment]
You're right! The issue was with my workflow.
