### ISSUE TITLE
FOP_CreateFormOfPayment 14.6.1A expiryDate without 0 at beginning

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#177]
Hey, I am trying to figure out the error with `expiryDate` in CC.

Error from Amadeus:
```
 Fusion DSC found an exception !\n\tThe data does not match the minimum length\n\tFor data element: expiryDate\n\tData length should be at least 4 and at most 4\n\tCurrent position in buffer: 818
```

The CC object I have (thats a fake card so no worries):
<img width="442" alt="screenshot 2018-04-10 23 42 12" src="https://user-images.githubusercontent.com/1025588/38585465-457b6b4c-3d1a-11e8-846a-1f33e2085f21.png">

I found the problem with WSDL but I have no idea how to fix it. I patched WSDL directly and it works...

Part of WSDL for expiry date:
```xml

      <xs:element name="expiryDate" minOccurs="0" type="NumericInteger_Length4To4">
        <xs:annotation>
          <xs:documentation xml:lang="en">Expiry date :  format    MMYY</xs:documentation>
        </xs:annotation>
      </xs:element>
```
Because it is `NumericInteger_Length4To4`, the SOAP casts it to integer and removes `0` from beginning. 
After changing it to `AlphaNumericString_Length4To4`, everything works. 

Any clue how to patch it on library level without patching WSDL? No problem for me, but maybe someone else will get the same issue in future.

**Comment by DerMika** [comment]
I have seen these kinds of errors before. Best would be to open a PTR with Amadeus and have them fix it. Of course this is a problem specific to how the PHP SoapClient converts the request object to XML.

Perhaps they'll be able to provide you an adjusted WSDL.

And otherwise as you say the only fix is to hack the WSDL yourself.

**Comment by DerMika** [comment]
I just found the other issue where something similar happened in SalesReports_DisplayQueryReport: Issue #59

**Comment by DerMika** [comment]
I have been thinking about your question of how to fix this on library level. 

The problem is that it would involve that the library edits the XSD file where the field in question is incorrectly configured. That's the only way, because `\SoapClient` works like that: it reads the WSDL and attached XSD's and converts based on the WSDL. 

Which makes 100% sense, since the WSDL is the contract between you and the server.

So even if we could keep a list of messages for which to edit specific nodes and edit the XSD files automatically, I'd rather not do it. It would be a lot of work to implement for something which is actually easily fixable. But more importantly, the problem here is the contract, the WSDL, is incorrect. So that's what should be changed, preferably by Amadeus, since they provide it :)

**Comment by DerMika** [comment]
Another option would be to do more editing on the outgoing XML in the `Amadeus\Client\SoapClient::__doRequest()`. 

We could decouple the current XSL transformation and provide an XSL transformation per message (or message version). That way we can make the actual transformation easier to read and we could add these kinds of message-specific exceptions. 

The problem there is that XSL transformations are a real nightmare to write :'(
