### ISSUE TITLE
UNABLE TO SATISFY, NEED CONFIRMED FLIGHT STATUS

### ISSUE THREAD

**Issue by XYNOMEX** [amabnl/amadeus-ws-client#186]
Hey,

3 days ago I was trying to book a flight and I got the following error message: "UNABLE TO SATISFY, NEED CONFIRMED FLIGHT STATUS", I tried to search for a reason in Amadeus system and I found that this error happens if the seat I'm trying to book is no longer available. today I tried to book the same flight and I got the same result. is it normal that Amadeus has such delay updating their database or it could be my search query that returns wrong results?
@DerMika @bimusiek

**Comment by DerMika** [comment]
Where do you get your flights from that you booked in the PNR? A MasterPricer call?

MasterPricer is a cached database system, so it's possible that it shows results that you can't proceed to book because those recommendations have been booked by someone else in the mean time. 

Did this error happen when calling AIR_SellFromRecommendation?

 You should always doublecheck and have a fallback flow to indicate to the user that this recommendation is no longer bookable when such an error happens.

Once it's booked into the PNR without a problem, you should price the PNR at the earliest possible time _(usually immediately after)_, giving you until the ticketing time limit to issue a ticket for the PNR (after which you're certain of the seat and the price).

**Comment by bimusiek** [comment]
We have the same issue. MasterPricer theoretically returns available fares (with availability counter). However, sometimes it can happen that when you try to book the fare is no longer offered or was just sold out. 

As @DerMika said, you need to have a flow in case of this error that it will notify user that this fare is no longer available and you have to do a new search or ask user to pick different flight. 
This does not happen very often but it is still there, especially for fares that are cheap & popular routes.

Our Amadeus microservice raises special exception so we know that fare is no longer available and then handle it on customer side.

```php
function sellFromRecommendation($itineraries) {
        $opt = new AirSellFromRecommendationOptions([
            'itinerary' => $itineraries
        ]);

        $sellResult = $this->client->airSellFromRecommendation($opt);
        if ($sellResult->status === Result::STATUS_OK) {
            return $sellResult;
        } else {
            $errorCode = $sellResult->messages[0]->code;
            if($errorCode == "288") {
                throw new FlightNotAvailableException();
            }
            throw new AmadeusResponseException($sellResult);
        }
    }
```

**Comment by therealartz** [comment]
In addition to previous answers, I want to confirm that is MPTB issue. 

It was explained that this is often happens in test/sandbox environment. However in production it also might happen, but not so often.

**Comment by XYNOMEX** [comment]
@DerMika @bimusiek  Your help is Appreciated, thanks a lot.
