### ISSUE TITLE
Fare_MasterPricerTravelBoardSearch additional options

### ISSUE THREAD

**Issue by ratheepan** [amabnl/amadeus-ws-client#20]
Hello Friend,
Thank you very much for amadeus library.
I am using this library for my Project.  My client have some additional features on Flight search (Fare_MasterPricerTravelBoardSearch)   i need some information on following scenario

1.  In round trip  search, is it possible to different cabinclass (eg Departure - Economy class and arrival First class)

2. How can i include Preferred airlines and Direct Flights Only option s in the request.

3.  Is it possible to have "My dates are flexible. [+/- 1 days]" search option
Could you please kindly share some examples request for  above option.

Thanks in Advance
S Ratheepan

**Comment by DerMika** [comment]
Hi, 

**Cabin class**
In the documentation of the `Fare_MasterPricerTraveLBoardSearch`, it is mentioned that you cannot request different cabin classes for the departure and for the return itinerary of a trip. 

You can select a requested cabin code for your MasterPricer recommendations, and optionally you can provide a cabin option:

- Mandatory Cabin: This cabin class applies to the entire requested itinerary. 
- Recommended Cabin: Cabin defaulting, when applicable, for flights that do not have the requested cabin service available. Note, however, that at least one of flight on each requested segment must propose the requested cabin in order to be eligible.
- Major Cabin option, the transaction replies with recommendations that are mostly flown in the requested cabin for each requested segment.

However, this library does not support the Cabin Option yet.

**Preferred airlines & direct flights**
Direct flights only is possible by providing the following option:

```
$options = new FareMasterPricerTbSearch([
    //other options omitted for clarity
    'requestedFlightOptions' => [
        FareMasterPricerTbSearch::FLIGHTTYPE_DIRECT
    ]
])
```
... But I went into the code just now and saw that the option actually isn't implemented.

The same goes for specifying preferred airlines:
```
$options = new FareMasterPricerTbSearch([
    //other options omitted for clarity
    'mandatoryAirlines' => ['DL', 'AA']
])
```
The option exists in my library, but it isn't implemented yet.

**Flexible days +/- 1**
This is also an option that is possible with `Fare_MasterPricerTravelBoardSearch`, but isn't implemented in the library yet.

I am putting all of these limitations on my to-do list, and they will be included in the next release.

**Comment by DerMika** [comment]
With the commit mentioned above, it's now possible to do the things you requested - except requesting a different cabin code for different itineraries (as explained above). 

Please see the docs for sample messages: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/masterpricertravelboard.rst

**Comment by fayax** [comment]
I'm getting this error with the latest commit for MPTB

Amadeus\Client\Result Object ( [status] => ERR [messages] => Array ( [0] => Amadeus\Client\Result\NotOk Object ( [code] => 936 [text] => Invalid time option [level] => ) ) [response] => stdClass Object ( [errorMessage] => stdClass Object ( [applicationError] => stdClass Object ( [applicationErrorDetail] => stdClass Object ( [error] => 936 ) ) [errorMessageText] => stdClass Object ( [freeTextQualification] => stdClass Object ( [textSubjectQualifier] => 1 ) [description] => Invalid time option ) ) ) [responseXml] => 9361Invalid time option ) 

Is there any bug or something I need to change on my end for the latest commit?

**Comment by DerMika** [comment]
It should be backwards compatible, if I didn't make any mistakes at least. Can you give me the Request Options so I can investigate?

And if you have a logger logging the requests & responses, can you also give me the generated request message? _(you should probably obscure things like passwords & usernames while doing that)_

**Comment by DerMika** [comment]
Ok, I just reproduced the error, I'm investigating.

**Comment by DerMika** [comment]
And it should be fixed now. Can you run `composer update` and try again?

**Comment by fayax** [comment]
Now it works perfectly. Thanks
