### ISSUE TITLE
amadeus ancillary services

### ISSUE THREAD

**Issue by arvind-pandey** [amabnl/amadeus-ws-client#208]
Hi @DerMika,
Thank you for creating excellent amadeus library in PHP. It is really helpful. 
I have started working on amadeus ancillary services, in which I have decided to use Service_StandaloneCatalogue  message. But the same is missing in this Library. 
It would be great if you can guide me in this.

**Comment by DerMika** [comment]
Hi! Thanks for your kind words!

It's going to be kind of hard for me to implement this message in a short timeframe since I don't have the time right now. If you have a month, or 2, I may be able to get it done, but no promises.

If you want to do it yourself, you're more than welcome! I wrote a [contributing guide](https://github.com/amabnl/amadeus-ws-client/blob/master/CONTRIBUTING.md) which also includes [some info](https://github.com/amabnl/amadeus-ws-client/blob/master/CONTRIBUTING.md#when-adding-a-new-message) on how to add support for a new message. 

If you have any questions during implementation, don't hesitate to ask!

**Comment by arvind-pandey** [comment]
Thank you for your response. I will surely try to implement this and will be in touch with you in coming days.

**Comment by arvind-pandey** [comment]
Hi @DerMika 
I have implemented Service_StandaloneCatalogue message on my local machine by referring your guideline for implementation of new message . Can you please guide me how to proceed to contribute on this library.

**Comment by arvind-pandey** [comment]
I have send you pull request for this message. Kindly share your feedback.

**Comment by DerMika** [comment]
#212 (linking for historical purposes)

**Comment by DerMika** [comment]
#220 (linking for historical purposes)

**Comment by DerMika** [comment]
Closing because the PR has been merged
