### ISSUE TITLE
passenger reference no automatically changed in PNR Response when adding APIs & SSR elements

### ISSUE THREAD

**Issue by rifkydj** [amabnl/amadeus-ws-client#261]
Hi Guys, 
When i adding multiple passengers to  PNR_AddMultiElements with  number 1 and 2 in reply it's changed as 2 and 3. when add more passengers also it changes?
Does this have any pattern? i couldn't identify any correct patterns .  please help me guys.

**Comment by rifkydj** [comment]
@DerMika . I meant was  i want to set APIs and SSR elements to passengers. sorry i didn't mentioned it. i apologize for that.  how can i achieve it? how can i make references to correct passenger to correct  Docs & SSR Items

**Comment by rifkydj** [comment]
@DerMika with pnr creation option code 0 can i do this? actually i want to set APIs & SSR elements with this. the passenger tatto number changes (elementManagementPassenger->reference->number) changes.How can i identify (pattern )this?

**Comment by DerMika** [comment]
You can't identify the pattern now the passenger tattoo is changed, that's why I suggested the method above to know how to link PNR passengers to users in your system.

The other option is to create passengers and add SSR / APIS elements in the same `PNR_AddMultiElements` message: In that case you can add a passenger association to an element using `Amadeus\Client\RequestOptions\Pnr\Reference::TYPE_PASSENGER_REQUEST` instead of `Amadeus\Client\RequestOptions\Pnr\Reference::TYPE_PASSENGER_TATTOO` (which means "link this to the passenger I identified with number X"). As Passenger Request number, you give the number you used in your `Amadeus\Client\RequestOptions\Pnr\Traveller::number`

**Comment by rifkydj** [comment]
@DerMika  Thanks alot. u saved my day. Thanks very much. i can close this issue now.
