### ISSUE TITLE
Create Ticket from PNR

### ISSUE THREAD

**Issue by Jaymaady** [amabnl/amadeus-ws-client#27]
Hello Sir, 

is it possible to create ticket from PNR (or alter pnrRetrieve message)?

Thanks in Advance

**Comment by DerMika** [comment]
Hi, 

In order to create a ticket from a PNR, the PNR must first be priced. The pricing messages supported are `Fare_PricePNRWithBookingClass`, `Fare_PricePNRWithLowerFares` and `Fare_PricePNRWithLowestFare`.

After you have successfully priced the PNR, you can issue a ticket for a priced PNR. This can be done with the `DocIssuance_IssueTicket` message. 

For the exact workflow, I suggest you read the implementation guides for Pricing and Ticketing which can be found on the [Amadeus Web Service Extranet](https://webservices.amadeus.com/extranet/functional_documentation.do).
