### ISSUE TITLE
difffernet session id for  Air_SellFromRecommendation  and pnr_addmultielements

### ISSUE THREAD

**Issue by Jaymaady** [amabnl/amadeus-ws-client#28]
Hello Sir
i am getting different **sessionid**  or  Air_SellFromRecommendation  and pnr_addmultielements

Both request i send with following params

$params = new Params([
           'sessionHandlerParams' => [
        'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
        'wsdl' => 'custom/include/Amadeus/Amadeus/1ASIWTNCHED_PDT_20161024_055327.wsdl', 
        'stateful' => true, 
    //    'logger' => new Psr\Log\NullLogger(),
        'authParams' => [
            'officeId' => 'MAAVSSS',
            'userId' => 'AAAAAAA', 
            'passwordData' => base64_encode('AMADEUS') 
        ]
    ],
    'requestCreatorParams' => [
        'receivedFrom' => 'my test project' // The "Received From" string that will be visible in PNR History
    ]
]);
$client = new Client($params);

Do i need add sessionid with second request.  ?
Could you kindly check that?

Thanks in Advance

**Comment by DerMika** [comment]
Hi, 

As long as you are using a stateful client (it seems like you do, since you have the `stateful` parameter set to `true`), the client will keep working in the same session as long as it is instantiated. Until you sign out of the current session of course.

So if you're getting a different Session ID between two messages, either the client is somehow running in stateless mode, or something caused you to sign out of your session, or a different instance of the client is used.

Also remember that once the PHP script has ended, all instances of the client will be destroyed. If you're in the situation where you need to persist session context between HTTP requests to your server, you will have to store your session information for example in the SESSION, or in some other kind of temporary storage, and when re-instantiating your client, you can continue working in the same session by providing the previous session's data to the client.

To achieve this, you can extract the current session's context by calling 

`$currentSessionData = $client->getSessionData();`

The result will be an associative array containing Session ID, Sequence Number and Security Token. When you instantiate a new client and you need to continue a previous session, you can provide the previous session's data by calling 

`$client->setSessionData($previousSessionData);`

Let me know if this solves your problem.

**Comment by Jaymaady** [comment]
Hello DerMika ,

Problem Solved,  

Thank you very much for your support.
