### ISSUE TITLE
ERROR AT END OF TRANSACTION TIME

### ISSUE THREAD

**Issue by humanyu** [amabnl/amadeus-ws-client#329]
I am getting sometimes following error while creating pnr

[status] => ERR
    [messages] => Array
        (
            [0] => Amadeus\Client\Result\NotOk Object
                (
                    [code] => 8111
                    [text] => ERROR AT END OF TRANSACTION TIME - ERROR AT EOT TIME - NEED ITINERARY
                    [level] => general
                )

        )

Please help me out

**Comment by therealartz** [comment]
Message says that need itinerary.
To create pnr it requires itinerary in it's context.

**Comment by humanyu** [comment]
I am already adding itinerary. It's occur sometime

**Comment by inodeas** [comment]
Hello, 

I am familiar with this and for me it was because the sell request (Hotel_sell ) failed at some point. Can you double check on that?

Cheers.

**Comment by humanyu** [comment]
It's happened while flight searching from USA OR long distance

**Comment by rifkydj** [comment]
Hi , 
I Think this problem occurs because of Air_SellFromRecommendation Haven't Created Amadeus Session. If it happens there will no itinerary will be created.

**Comment by humanyu** [comment]
What should I do??

**Comment by DerMika** [comment]
You need to check a few things: 

- Since you only get this error sometimes and not all the times, I am assuming you are using stateful sessions where needed
- as @rifkydj says, check the responses of your previous messages. Either the Air_SellFromRecommendation responded with an error,or something else happened to your PNR, causing the itinerary you are booking to fail.

So my answer would be: check the logs of the flow leading up to this error.
