### ISSUE TITLE
PnrAddMultiElementsBase actionCode

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#34]
Hey, I see that you can only pass 1 action code to `PnrCreatePnrOptions `.
Can you tell me if it is possible to pass many options?

Via Amadeus TechRef for AddMultiElements you are able to pass up to 40 action codes, and my amadeus manager asked us to pass 3 codes :(

**Comment by DerMika** [comment]
Hi, 

The actionCode in the message is the action code that will be sent as the XML node `PNR_AddMultiElements/pnrActions/optionCode` in the PNR_AddMultiElements message. If you check the XSD's on the Amadeus Web Services Extranet, you see that in theory the `optionCode` node can indeed occur up to 40 times according to the XSD definition, as you say.

However, in practice, I have never seen any example of a `PNR_AddMultiElements` message where more than 1 `optionCode` is sent, and I don't believe that it is _actually supported_ by Amadeus.

It is the intention of my library to remove any unnecessary complexity that exists in the Amadeus Web Services, which is why I tend to implement the simplest possible set of options that _actually works_.

So, as far as I am concerned, one `optionCode` is all that will ever be used. If you can provide me a functional example of a `PNR_AddMultiElements` message with multiple optionCodes and why it requires multiple optionCodes, i'd be more than happy to implement a fix. But I don't think you'll find one.

**Some more explanation:** 
The `optionCode` element determines what happens with the PNR (End Transact, End Transact & Retrieve, Ignore, Ignore & Retrieve, etc), so it really doesn't make sense to do both an End Transact and an Ignore at the same time, they would be mutually exclusive. This makes me think that only single optionCodes are actually supported on Amadeus side. But feel free to investigate for yourself!

**Comment by bimusiek** [comment]
Hi,
I understand your point and I was really suprised when they asked me to send 3 codes. 

Here is what I am doing and why Amadeus asked me to change it.
1. I do Air_SellFromRecommendation in stateful session
2. Then I do AddMultiElements to add names, phone numbers etc with option code 11 (save and retrieve)

However from documentation about optionCodes
<img width="555" alt="screen shot 2016-12-13 at 16 18 13" src="https://cloud.githubusercontent.com/assets/1025588/21145801/d98f5a34-c14f-11e6-8903-2b8960501330.png">
you can combine 11 with 30 + 267.

And from the user guide on webservices, 
```
Names Elements
When creating a name item within this function the following information should be noted:
There is no special processing required for adding a name element. Therefore, the mandatory option code is set to 0.
```
you have to set 0 when calling `PNR_AddMultiElements` with phones, names etc.

Then you do empty call with these 3 codes: 11, 30, 267

So what they told me is that flow should look like:
1. SellFromRecommendation
2. AddMultiElements with all the passenger details (code: 0)
3. AddMultiElements with 11, 30, 267 codes. 

Does it explain it?

**Comment by DerMika** [comment]
Well, you learn something new every day. I had never encountered this situation before and didn't know that this possibility existed. 

As far as I know, this scenario is not documented on the Web Services Extranet? Is it in some kind of implementation guide?

Ok, I'll develop a fix to support multiple option codes.

**Comment by bimusiek** [comment]
It is in extranet, in both pdfs and in user guides. 
Thank you very much! :)

**Comment by DerMika** [comment]
I've added support for this in the master branch now, to be released with version 1.2.0. 

See the docs for an example: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#multiple-action-codes-optioncode

If you have any problems with it, don't hesitate to open a new issue or reopen this one!

**Comment by bimusiek** [comment]
Thanks, just tested and it works as expected :) 
I am waiting for confirmation from Amadeus Dev team to confirm it is ok now.

**Comment by bairuhatech** [comment]
does anyone have sample xml code for requests for each option
