### ISSUE TITLE
getLastResponse() and getLastRequest() return null

### ISSUE THREAD

**Issue by ahmedsalim2021** [amabnl/amadeus-ws-client#436]
When did I call two methods of client getLastRequest() and getLastResponse() to log XML response and request it returns null and I don't know why?

**Comment by joseayram** [comment]
Hello! 

The methods getLastRequest and getLastResponse must be called after you call to the message, ex:

`
$client = new Client($params);
$options = new FareMasterPricerTbSearch([
      'nrOfRequestedResults' => 10,
      'nrOfRequestedPassengers' => 1,
      'passengers' => $passengers,
      'itinerary' => $itinerary,
      'requestedFlightTypes' => $flightTypes,
]);
$result = $client->fareMasterPricerTravelBoardSearch($options);
// If you call this methods before this return empty
$lastMessageSent = $client->getLastRequest();
$lastResponseReceived = $client->getLastResponse();
`
I don't like this methods, because the return it's in plain text without tags and is very hard to me read that. (maybe I'm doing something wrong).

I use this way to logs requests and responses: [Logging Request and Response](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response)

**Comment by ahmedsalim2021** [comment]
@joseayram  Thanks for your reply
these methods return string XML with tags
and yes I call them after calling the message
I couldn't use log because the output is text and log file become a hug

Still return null after calling messga
