### ISSUE TITLE
Adding the SR DOCS element with more than one passenger (Passenger ID issue with TYPE_PASSENGER_TATTOO)

### ISSUE THREAD

**Issue by zakch17** [amabnl/amadeus-ws-client#58]
Hi, 

I have a clear issue.

When we have more than one traveller, and we require to add the SR DOCS with the identifier of each traveller (TYPE_PASSENGER_TATTOO). The ID's first traveller does start from **2** and not **1**. Thus when adding the SR Docs information we have to consider that traveller 1 has ID=2 and traveller 2 Has ID=3 and so on...
In this way, it works normally. Check the attached screen which depicts the creation of two travellers.

![capture](https://cloud.githubusercontent.com/assets/9497271/24553247/80e0a632-1621-11e7-8209-350e489024ee.PNG)

**Comment by DerMika** [comment]
Is this 1 PNR_AddMultiElements where you are adding passengers as well as SRDOCS? Or are you adding SRDOCS to a previously created PNR?

If it's the first, you need to use `TYPE_PASSENGER_REQUEST` instead of `TYPE_PASSENGER_TATTOO` which means: "use the ID I've provided for this passenger". [See previous issue here](https://github.com/amabnl/amadeus-ws-client/issues/50#issuecomment-287724330)

**Comment by zakch17** [comment]
I do confirm it's working perfectly the way you described.
