### ISSUE TITLE
PNR Modification

### ISSUE THREAD

**Issue by nikhildeshmukh** [amabnl/amadeus-ws-client#67]
What level of PNR modification does this library supports.
Can i get an example steps for sending messages.
for e.g 
Like if i had already generated a pnr and i need to modify so how to proceed ?

**Comment by DerMika** [comment]
What this library does is no more than allowing you to perform specific SOAP messages on the Amadeus Web Services.

So any message and message feature that has been implemented works just as described in the Amadeus docs.

For the scenario you mention, this is perfectly possible. First of all you need configure the client to use a  [stateful session](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4) because you'll need to retain your context between messages. 

Then you need to retrieve a PNR with the `pnrRetrieve()` method. By doing that you have "opened" the PNR and it will be available to perform further actions on it. Most actions in a PNR are done using the `pnrAddMultiElements()` method or the `pnrCancel()` method which allow you to respectively add and remove specific PNR elements, segments, or passenger information. 

For example, if you want to add a RM (general remark) to a PNR which has been put into context, you just send something like this:

```php
use Amadeus\Client\RequestOptions\PnrCreatePnrOptions;
use Amadeus\Client\RequestOptions\Pnr\Element\MiscellaneousRemark;

$addResult = $client->pnrAddMultiElements(
    new PnrAddMultiElementsOptions([
        'actionCode' => PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE
        'elements' => [
            new MiscellaneousRemark([
                'text' => 'This is a general remark'
            ])
        ]
    ])
);
```

By providing the actionCode `PnrAddMultiElementsOptions::ACTION_END_TRANSACT_RETRIEVE` you indicate that after adding the Remark, the updated PNR must be saved and re-retrieved. The response will contain the updated PNR after adding the element _(but it could contain errors if the element you've tried to add was somehow invalid)_

Also, by re-retrieving the PNR, you have effectively placed the PNR in context again, ready for further actions on the PNR.

Also, after using a stateful session, don't forget to sign out (with the `securitySignOut()` method).

**Comment by nikhildeshmukh** [comment]
thanks but can you give me a example of changing segments
will be helpfull

**Comment by DerMika** [comment]
I don't have any ready samples, but I can tell you how to do it. 

Basically, unless you're using a specific message like `Air_RebookAirSegment` _(which isn't supported in this library right now)_, you need to first cancel the existing segment and then add the new segment. Just like you would do in Amadeus Selling Platform (= an `XE` cryptic entry followed by an entry to add the new segment).

First of all, you need to do a pnrRetrieve(), and find the Segment Tattoo for the segment you want to remove (can be found at `/PNR_Reply/originDestinationDetails/itineraryInfo/elementManagementItinerary/reference/number` in the PNR_Reply). This will give you the Tattoo number of the segment to remove.

Then you do a `pnrCancel()` as explained in the second example [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#pnr-cancel). _Contrary to that example, in this case I would only do the ACTION_END_TRANSACT_RETRIEVE action when you have cancelled the old and added the new segment._ 

After that you add the new segment in any way you would otherwise add a new segment. Via `airSellFromRecommendation()` - [example](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#air-sellfromrecommendation) - or by manually adding an AIR segment via `pnrAddMultiElements()` - [example](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples/pnr-create-modify.rst#adding-a-single-air-segment).

**Comment by DerMika** [comment]
Hi, 

Is your question answered? If so, can you please close the issue?

**Comment by bimusiek** [comment]
I just want to point out that in ATC documentation there are 2 notes explaining when to cancel first and then add new segments or when to add new segments (to make sure these are available) and then cancel previous ones 👍 

All can be found in ATC Guide and because I already read all of it twice I can say that they explained everything there.

**Comment by nikhildeshmukh** [comment]
thanks @DerMika @bimusiek
