### ISSUE TITLE
Request for Service_IntegratedCatalogue implementation

### ISSUE THREAD

**Issue by zhaonan0218** [amabnl/amadeus-ws-client#80]
This is a request for message Service_IntegratedCatalogue implementation that is in the to-do list, thank you very much! 👍

**Comment by DerMika** [comment]
I don't have the time right now to implement this. 

For anyone who wants to do this, check out a rough guideline of how to do this in [this comment](https://github.com/amabnl/amadeus-ws-client/issues/79#issuecomment-311026268) on issue #79

**Comment by DerMika** [comment]
Hi, can you please list which options of this message you'd need? I'd like to try to implement at least basic support for this message.

**Comment by zhaonan0218** [comment]
Sorry DerMika, just saw your reply. The data we are trying to retrieve from this message are the list of services names/descriptions/names.
Thank you!

**Comment by DerMika** [comment]
I finally implemented this message. Turns out it wasn't a lot of work, since the messages structure and options are identical to `Service_IntegratedPricing`! Check out the [documentation](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/samples.rst#service-integratedcatalogue).

You can test the message by switching your `composer.json` to `dev-master`. 

Support for this message will be released in the 1.5.0 release.

**Comment by DerMika** [comment]
Version 1.5.0 has been released.
