### ISSUE TITLE
 file_get_contents(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by MyDcode** [amabnl/amadeus-ws-client#81]
Hi, First of all Thank you very much for your support so-far for the community.

I am running your library in the local host and getting the following error.

> file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed 2 _full_path_\Amadeus\Client\Session\Handler\WsdlAnalyser.php 222

And I understand this error caused because of the local SSL settings, just for you information I have setup for ssl in windows vhost and in the xampp config as well.

I got the same issue when I develop my own library for amadeus ws, and I did

```
$this->client = new SoapClient($wsdl,
            array(
                "trace" => TRUE,
                "stream_context" => stream_context_create(
                    array(
                        'ssl' => array(
                            'verify_peer'       => false,
                            'verify_peer_name'  => false,
                        )
                    )
                )
            )
        );
```

and above code seems to solve that issue... 

Now I need your support how to give this kind a setup in your library, or is there any-other possible way to resolve above error.

Thank you.

**Comment by DerMika** [comment]
Yes, you can provide additional SoapClient setup options. It's described in the docs [here](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#custom-soapclient-options)

so in your case you'd do this: 

```php
use Amadeus\Client\Params;

$params = new Params([
    'sessionHandlerParams' => [
        // ...
        // other parameters omitted for clarity
        // ...
        'soapClientOptions' => [
            'trace' => true,
            'stream_context' => [
                'ssl' => [
                    'verify_peer' => false,
                    'verify_peer_name'  => false,
                ]
            ]
        ]
    ]
    'requestCreatorParams' => [
        'receivedFrom' => 'my test project'
    ]
]);
```

Please let me know if this fixes your problem!

**Comment by DerMika** [comment]
In fact, you don't have to add the 'trace' parameter. This library enables the trace feature by default.

**Comment by MyDcode** [comment]
DerMika, thank you so much for your valuable time and respond. I found another way as well, what I did just put my WSDL documents outside the root file and mapped the location to it.

Magically everything is working perfect. You saved lot of my time with this library thank you very much.

Also wanted clarify, when I use the securityAuthenticate() function its returning an error code saying you have already logged in and suggesting me to logout then use.

So, What I did just before passing the securityAuthenticate() method I passed the securitySignOut(), still same error occurred. any guesses?

By the way once again thank you so much.

**Comment by DerMika** [comment]
If you are using a SoapHeader 4 WSAP _(which you probably are if you have recently started a new project with Amadeus),_ there is no need to send a separate authentication call. 

The library will set the necessary SOAP headers to automatically authenticate when you're sending the initial call to the SOAP server. If you've configured the client to use [stateful sessions](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#switching-between-stateful-stateless-messages-soap-header-4), the library will keep sending messages in the same session until you [sign out](https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#ending-a-stateful-session-soap-header-4). Otherwise, you're sending stateless messages where each message will include the needed authentication headers.

I'm closing this issue now since your original problem seems to be solved.

**Comment by MyDcode** [comment]
Got it! Thank you.
