### ISSUE TITLE
Context Required Services

### ISSUE THREAD

**Issue by ldjvc** [amabnl/amadeus-ws-client#9]
I'd like to implement the TicketDisplayTSMP service but I'm not sure how to "get" a PNR context with this library. I can't see any option in my PNR_Retrieve WSDL that indicates to "keep" a retrieved PNR in context. I can retrieve a PNR, works fine, but how to keep in context? Any help appreciated.

**Comment by DerMika** [comment]
First of all, you have to make sure you're using a stateful session of course, because any context gets lost when the session gets closed.

Then, by doing a `PNR_Retrieve` query, you have implicitly placed this PNR 'in context'. 

Doing a PNR_Retrieve call is equivalent with performing a cryptic `RT<RECORDLOCATOR>`  entry on Amadeus Selling Platform: you have "opened the file".

When working with a PNR with PNR_AddMultiElements, it's the `actionCode` option (see https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/RequestOptions/PnrAddMultiElementsBase.php#L33) that will determine if - after performing a PNR_AddMultiElements - the PNR is still in context or not:

Action codes 0, 11, 21 are examples of action codes that keep the PNR in context.

0: the PNR doesn't get saved, it stays open
11: equivalent to a cryptic `ER` (end and retrieve) entry in Selling Platform: save the PNR and re-retrieve it.
21: equivalent to a cryptic `IR` (ignore and retrieve) entry in Selling Platform: ignore your changes in the PNR and re-retrieve it.

I hope this helps!

**Comment by ldjvc** [comment]
Hi Dieter, thanks for the response, that's a big help. I didn't think it would be that easy. I was looking for a manual option to retain context. Thanks again.

**Comment by DerMika** [comment]
The rule of thumb is: when in doubt with the Amadeus Web Services, assume it works analogous to Amadeus Selling Platform. But not many people outside Amadeus have much knowledge about that program. That makes developing on these web services a bit difficult & cumbersome...

**Comment by DerMika** [comment]
Also, if you'd like to contribute any new messages you implement in a pull request, that would be awesome :)

**Comment by ldjvc** [comment]
Thanks for the advice. I'll keep that in mind. Once I get the service working I'll submit a pull request. Thanks again.

**Comment by tommiehansen** [comment]
Btw -- this 'context' was very simple to achieve but it was a bit fiddly since no documentation really exist so one sort of has to get how things work without knowing it. :)

Here's it working via a Cryptic Emulator i built:

![image](https://cloud.githubusercontent.com/assets/8710941/20602199/7d18852a-b25c-11e6-936b-a322a1037e9a.png)

The context is simply achieved by re-using a  a previously saved session (via a dirty file caching solution) if the time is under X (since Amadeus has a timeout of around 35-45 minutes).

Here's some **dirty code** for anyone wondering how to achieve and keep a `context` in Amadeus:

#### Load lib stuff

```
// ns
use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\Result;
use Amadeus\Client\RequestOptions\CommandCrypticOptions;


// amadeus default params
$params = new Params([
    'sessionHandlerParams' => [
        'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
        'wsdl' => $conf->amadeus->wsdl,
        'stateful' => true, // Enable stateful messages by default - can be changed at will to switch between stateless & stateful. Stateful = create session per user; need stateful stuff for PNR's etc
        'logger' => new Psr\Log\NullLogger(),
        'authParams' => [
            'officeId' => $conf->amadeus->officeId, // The Amadeus Office Id you want to sign in to - must be open on your WSAP.
            'userId' => $conf->amadeus->user, // Also known as 'Originator' for Soap Header 1 & 2 WSDL's
            'passwordData' => base64_encode($conf->amadeus->pass), // **base 64 encoded** password
        ]
    ],
    'requestCreatorParams' => [
        'receivedFrom' => $conf->amadeus->fromUser, // The "Received From" string that will be visible in PNR History
    ]
]);


$client = new Client($params);
```

#### Dirty file-caching and check for session (context)

```
$ip = $_SERVER['REMOTE_ADDR']; // use ip per user to create session (temp)
$ip = str_replace('.','',$ip);
$ip = str_replace(':','_',$ip);
$cacheFile = $config->cache->dir . 's' . $ip . '.sess'; // save as s + ip + .sess
$cacheTime = $config->cache->time;
$exists = file_exists($cacheFile);

if( !$exists || ( $exists && time() > strtotime('+ ' . $cacheTime, filemtime($cacheFile)) )) {
    // do nothing, we must write session **AFTER** contact with amadeus -- else won't have any.
   $hasSession = false;
}
else {
      // use previous session
    $hasSession = true;
    $sess = file_get_contents($cacheFile);
    $sess = json_decode($sess, true);
    $client->setSessionData($sess); // set it
}
```

#### Do command and create + save session (context) if $hasSession = false

```
// default (for testing etc)
$command = "DAC NYC";

// $_POST function --- roll your own!
if(_P('c')){
    $command = strtoupper( _P('c') );
}
else {
   die('Commands are cool!');
}

$opt = new CommandCrypticOptions([
    'entry' => "$command"
]);

$cryptic = $client->commandCryptic($opt);
$response = $cryptic->response;
$data = $cryptic->response->longTextString->textStringDetails;

// write to session if one wasn't available
if( !$hasSession ){
    $sess = $client->getSessionData(); // create new session
    $sess = json_encode($sess);
    file_put_contents($cacheFile, $sess);
}
```

**Comment by DerMika** [comment]
I'm interested why you need to keep an unsaved PNR in context for over 45 minutes. I don't really see a reason to do that. 

In my opinion, it's better to save the current status of a PNR to Amadeus and re-retrieve a PNR when needed, than to leave an unsaved situation lingering.
